name: FTP Deploy

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    name: FTP Deploy Job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Build the Website
        run: npm run build

      - name: Deploy to Hostinger FTP
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          server: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          protocol: ftp
          local-dir: dist/
          server-dir: ${{ secrets.REMOTEFOLDER }}/
